project:
  type: website

website:
  title: "About Econ"
  navbar:
    left:
      - about.qmd
      - href: apply.qmd
        text: Econ Applying
      - href: resources.qmd
        text: Econ Resources
      - href: field.qmd
        text: Econ Resoures II

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

