---
title: "Macro"
toc: true
number-sections: true
---

These mainly some specific fields in Macroeconomics and Macro-Fiannce.

> The classification may be overlapped.

<!-- Speically thanks for the [collections](https://www.zhihu.com/search?type=content&q=%E7%BB%8F%E6%B5%8E%E5%AD%A6%E7%9A%84lecturenote) on zhihu -->

<!-- - EC702<https://github.com/amckay/EC702> -->
<!-- - <https://github.com/KateSchneider-FoodPol/Stata-Regression-Teaching-Exercise> -->


## Heterogeneous Agents Model

- <https://www.nber.org/conferences/heterogeneous-agent-macro-workshop-spring-2022> NBER Heteregenous-Agent Macro Workshop 2022

- <https://www.ralphluetticke.com/files/Slides_Luetticke.pdf> The author's [github page](https://github.com/ralphluet)

- Computational Notes on Heterogeneous-Agent Macroeconomics <https://alisdairmckay.com/Notes/HetAgents/>

- Notes on Computational Methods for Macroeconomics <https://makotonakajima.github.io/comp/> by [Makoto Nakajima](https://makotonakajima.github.io/)

- Codes mainly related to HANK <https://www.ralphluetticke.com/code/>

## DSGE

- <https://github.com/FRBNY-DSGE/DSGE.jl> The DSGE in Julia

- <http://web.stanford.edu/~aauclert/kuleuvenmini/> Minicourse on Fiscal and Monetary Policy with Heterogeneous Agents

- [Rios-Rull Slides](https://www.sas.upenn.edu/~vr0j/fslides.html)

- [Econ807](https://docs.google.com/a/umn.edu/viewer?a=v&pid=sites&srcid=dW1uLmVkdXxjaGFyaXxneDozMDgyOWRlYzlmOWU0NWMw) and [problem sets](https://sites.google.com/a/umn.edu/chari/teaching)

- A collection of Dynare models <https://github.com/JEFFSAMUEL/SANA/tree/20caa600c5508649011a4f1da7d7a57401fc4d4d>


## Macro-Finance

- <https://www.isaacbaley.com/advanced-macro-ii.html>

- <https://sites.google.com/a/nyu.edu/advanced-macroeconomics-i/products-services>

<!-- - MARTIN ELLISON<https://users.ox.ac.uk/~exet2581/index.html> -->

- Dean Corbae Teaching in UWM <https://sites.google.com/a/wisc.edu/deancorbae/teaching>

- jesusfv's website includes [Course on Computation](https://www.sas.upenn.edu/~jesusfv/teaching.html)&[Courses on Macroeconomics](https://www.sas.upenn.edu/~jesusfv/teaching.html) and Course on History.

- <https://sites.bu.edu/perry/lectures/mb-lectures/section-1/> Banking


## Asset Pricing

- François Gourio(Federal Reserve Bank of Chicago) Teaching Page <https://sites.google.com/site/fgourio/teaching-notes?authuser=0> including macro-asset pricing and PhD-level macroeconomics

- <http://pfwang.people.ust.hk/Teaching.htm>

- Wuhan University FinTech <https://github.com/WHUFT> 

- [Quantitive Investment](https://abzhaobo.github.io/courses/quant/) in NanKai University 

- [Big data and Asset Prising](https://www.lhpedersen.com/big-data-asset-pricing)

- [Open Source Asset Pricing](https://www.openassetpricing.com/code/)

- <http://www.hengjieai.com/intro-to-ap.html> 

- <https://www.factorwar.com/research/asset-pricing/> 

## Dynamic Model

- [Firm Dynamics](http://www.chrisedmond.net/phd2014.html) taught by Chris Edmond(U Melbourne).

- [Deep Learning for Solving and Estimating Dynamic Models](https://dseconf.org/dse2023#)


## Lecture note/textbook

> The Published Textbooks are limited to printing right such that these could not be accessed the pdf files in a general way.

- [Time Series Analysis](https://press.princeton.edu/books/hardcover/9780691042893/time-series-analysis)
- [LS](http://libgen.rs/search.php?req=recursive+macroeconomic&open=0&res=25&view=simple&phrase=1&column=def)
- [SLP](http://libgen.rs/search.php?req=recursive+methods&open=0&res=25&view=simple&phrase=1&column=def)
- [Monetary Policy,inflation, and the Business Cycle](http://libgen.rs/search.php?req=Monetary+Policy%2C+Inflation%2C+and+the+Business+Cycle&open=0&res=25&view=simple&phrase=1&column=def) The classic textbook in NK.
- Applied Computational Economics and Finance
- Economic Growth 
- Theory and numerical solution methods
- Dynamic General Equilibrium Modeling.
- Bayesian Estimation of DSGE 

## Math

- Alexis Akira Toda Teaching List, including Mathematical Economics, Financial Markets, and Intertemporal Asset Pricing Theory <https://alexisakira.github.io/teaching/>
- [Calculus of Variations and Partial Differential Equations](https://www.math.tecnico.ulisboa.pt/~dgomes/notas_calvar.pdf)
- <https://sites.bu.edu/perry/lectures/mb-lectures/section-1/>
- <https://press.princeton.edu/books/hardcover/9780691135052/the-economics-of-inaction> writed by Nancy Stockey


### SDE/BDSE/Stochastic Controls

- Financial Modeling:A Backward Stochastic Differential Equations Perspective <https://link.springer.com/book/10.1007/978-3-642-37113-4>
- Stochastic Controls: Hamiltonian Systems and HJB Equations  <https://www.amazon.com/Stochastic-Controls-Hamiltonian-Equations-Probability/dp/0387987231>


### Mean Field Games 

- <https://arxiv.org/abs/1509.02505>: The master equation and the convergence problem in mean field games
- <https://arxiv.org/abs/2012.05237> Applications of Mean Field Games in Financial Engineering and Economic Theory
- Ben Moll(LSE) <https://benjaminmoll.com/wp-content/uploads/2020/10/MFG_macro.pdf>
- Adrien Bilal(Harvard) [ECONOMICS AND MEAN FIELD GAMES](https://sites.google.com/site/adrienbilal/teaching)

## Quantitative Macro Econ/ Micro data

- Empirical Macro <https://eml.berkeley.edu/~enakamura/teaching.html> Emi Nakamura.

- <https://sites.google.com/site/dimitriskorobilis/teaching> by [Dimitris Korobilis](https://sites.google.com/site/dimitriskorobilis/home-1)

- Applied Macroeconomics using Python <https://github.com/marcinbielecki/Applied_Macroeconomics>

- [Methods and Applications in Quantitative Macroeconomics](https://sites.google.com/site/katrinrabitsch/teaching/quantmacro2012)

- [Computational Methods for Economists](https://lmaliar.ws.gc.cuny.edu/teaching/computational-methods-for-economists/) taught by Lilia Maliar(CUNY) whom also wrote the book chapter in [Handbook of Computational Economics](https://lmaliar.ws.gc.cuny.edu/files/2019/01/Chapter7HandbookCE2014.pdf)

- <https://www.thomaswinberry.com/teaching/index.html>Micro Data for Macro Models [Reading list](https://www.thomaswinberry.com/teaching/winberryReadingList_2019.pdf)

- Advanced topics in applied macroeconomics<https://scholar.harvard.edu/chodorow-reich/classes/economics-2410hfc-advanced-topics-applied-macroeconomics> by Gabriel Chodorow-Reich

- <http://www.wouterdenhaan.com/software.htm>

- <https://benjaminmoll.com/lectures/> benjaminmoll 

- <https://markus.scholar.princeton.edu/MacroMoneyFinance> MacroMoneyFinance taught by Markus Brunnermier.


## Others

<!-- - Deep Learning Tutorial<http://ufldl.stanford.edu/tutorial/> -->
<!-- - Understanding LSTM <https://colah.github.io/posts/2015-08-Understanding-LSTMs/> -->
- <https://wp.nyu.edu/zhenhuan/resources/> collected by Leed Lei.
- Reading List in Macroeconomics and Monetary Economics <https://integdomain.files.wordpress.com/2014/07/monetary_list_v1-11.pdf>
- [Scientific Research and Methodology](https://bookdown.org/pkaldunn/SRM-Textbook/) This book introduces quantitative research in the scientific and health disciplines. But it still works in other disciplines.
- [Four Steps to an Applied Micro Paper](https://scholar.harvard.edu/files/shapiro/files/foursteps.pdf)
- [writting suggesting](https://static1.squarespace.com/static/57d5edcf197aea51693538dc/t/5f975fd031e9ee561a6dbd19/1603755986109/writing_0.pdf), Ryan Edwards
- [How to build an economic model in your spare time](https://people.ischool.berkeley.edu/~hal/Papers/how.pdf), Hal Varian


